### ISSUE TITLE
Add custom products

### ISSUE THREAD

**Issue by maxtar** [porscheinformatik/cucumber-report-db#13]
Can I somehow add my project to the products list? Now they are hardcoded. And I want rename "collection_version" to another name.

**Comment by klausbayrhammer** [comment]
@maxtar the products should be loaded via the database. Could you give it a try?

**Comment by user3** [comment]
Ich bin bis 07.01.2015 abwesend.




Hinweis: Dies ist eine automatische Antwort auf Ihre Nachricht  "Re:
[cucumber-report-db] Add custom products (#13)" gesendet am 04.01.2015
20:57:05.

Diese ist die einzige Benachrichtigung, die Sie empfangen werden, während
diese Person abwesend ist.=

**Comment by maxtar** [comment]
@klausbayrhammer Sorry for long answer. I on holidays till 12 of Jan. I'll try when return to work. :)

**Comment by maxtar** [comment]
@klausbayrhammer hi. I added -Dcucumber.report.collection.name=project to JVM arguments, but nothing changed. I have only one product - "collection".

**Comment by klausbayrhammer** [comment]
@maxtar The name of the collection specified by ```cucumber.report.collection.name``` has to be in the form productname_version (the underscore is necessary). In commit c96b4c290bb47d44443b18d4a762051b8d36e29e I've added specific system properties for the product name ```cucumber.report.product.name``` and product version ```cucumber.report.product.version```.

Now you can specify the name of the collection via 
* ```-Dcucumber.report.collection.name=productA_1.2.0``` -> results in collectionname productA_1.2.0
* ```-Dcucumber.report.product.name=product -Dcucumber.report.product.version=1.2.3-SNAPSHOT```  -> results in collectionname product_1.2.3-SNAPSHOT
*  ```-Dcucumber.report.product.name=product``` -> (with version default 1.0) results in collectionname product_1.0

**Comment by maxtar** [comment]
@klausbayrhammer Sorry, I don't understand. I set following settings:
 -Dcucumber.report.product.name=Boor -Dcucumber.report.product.version=MySNAPSHOT -Dcucumber.report.collection.name=FF
But in web-interface I see only
"Product / Version	Statistics
collection_version	Charts"

**Comment by klausbayrhammer** [comment]
You have to set the properties for the process you use for your cucumber-tests  with the MongoDBFormatter.Like ```java -cp ..... cucumber.api.cli.Main -f at.porscheinformatik.cucumber.formatter.MongoDbFormatter -Dcucumber.report.collection.name=productA_1.2.0 myFeature.feature```

The idea behind this was to have a single web-application which stores all test-results from different products and versions. When you execute your cucumber-tests each test-run knows what product and version is tested and publishes the information to the web-application. So one test-run only tests one product/version but the webapp stores information on test-runs of different products and versions.

Hope to help

**Comment by maxtar** [comment]
Yes, i have following run string
"java -Dcucumber.report.server.baseUrl=http://localhost:8080 -Dcucumber.report.product.name=Boor -Dcucumber.report.product.version=MySNAPSHOT -Dcucumber.report.collection.name=FF -Dfile.encoding=UTF-8 -classpath ... cucumber.api.cli.Main --format at.porscheinformatik.cucumber.formatter.MongoDbFormatter --monochrome --glue ... 
My.feature"

**Comment by klausbayrhammer** [comment]
Hm that looks correct. In the webapp you should have a couple of logs like ```
08:52:40.662 [http-nio-8081-exec-2] INFO  a.p.c.m.r.c.CucumberPluginController - insert report into collection Boor_MySNAPSHOT```
Is the collection name in the logs correct? And can you see the data of the new testrun in the webapp?

**Comment by maxtar** [comment]
No, I see only strings like this:
"18:28:19.664 [http-nio-8080-exec-8] INFO  a.p.c.m.r.c.CucumberPluginController - insert report into collection collection_version
19:40:58.062 [http-nio-8080-exec-9] INFO  a.p.c.m.r.c.CucumberPluginController - insert report into collection collection_version
19:44:46.530 [http-nio-8080-exec-10] INFO  a.p.c.m.r.c.CucumberPluginController - insert report into collection collection_version"

**Comment by klausbayrhammer** [comment]
Is it possible, that you use an older version of the formatter? In c96b4c290bb47d44443b18d4a762051b8d36e29e I've changed the fallback collectionname from "collection_version" to "product_version". So in the current version of the formatter you should see a log like ```INFO a.p.c.m.r.c.CucumberPluginController - insert report into collection product_version```

**Comment by maxtar** [comment]
Strange. I've got last version yesterday. Will try one more time.

**Comment by maxtar** [comment]
Sorry. I got it! You have changed version, but I didn't notice these. And didn't change in my pom dependencies. All OK, except I doesn't see collection name from cucumber.report.collection.name property

**Comment by klausbayrhammer** [comment]
The collection-name has to be in the form product_version - the underscore is necessary. Like ```-Dcucumber.report.collection.name=FF_mySnapshot```Otherwise the data is filtered and not shown in the webapp.

**Comment by maxtar** [comment]
Ok. have changed to F_F. Nothing changed.

**Comment by klausbayrhammer** [comment]
Hm. Do you have a log-entry ```INFO a.p.c.m.r.c.CucumberPluginController - insert report into collection F_F```? Can you see the results of that test-run unter the "collection_version" or "product_version" product?

**Comment by maxtar** [comment]
No, I haven't. Just "12:13:12.730 [http-nio-8080-exec-9] INFO  a.p.c.m.r.c.CucumberPluginController - insert report into collection Boor_MySNAPSHOT
12:30:00.902 [http-nio-8080-exec-4] INFO  a.p.c.m.r.c.CucumberPluginController - insert report into collection Boor_MySNAPSHOT

**Comment by klausbayrhammer** [comment]
Hm and you don't see an entry Boor_MySNAPSHOT on the product overview or the entry "Boor" in the product dropdown on the menu?

When you start with ```-Dcucumber.report.product.name=Boor -Dcucumber.report.product.version=MySNAPSHOT -Dcucumber.report.collection.name=FF``` the collection name is a combination of product.name and product.version. If you start with ```-Dcucumber.report.collection.name=F_F``` the collection-name is F_F.

Do you have any exceptions/stacktraces in the webapp-log?

**Comment by maxtar** [comment]
Yes. I have "Boor" product in dropdown list. I haven't any exceptions.
I'm properly understand that I need set or -cucumber.report.product.name, cucumber.report.product.version or just only cucumber.report.collection.name properties?

**Comment by klausbayrhammer** [comment]
Yes exactly. You can either specify:
* cucumber.report.product.name and cucumber.report.product.version
* cucumber.report.collection.name (in the form product_version)

**Comment by maxtar** [comment]
Iv'e got it, Klaus. I think will be better add this description to the documentation. :)

**Comment by klausbayrhammer** [comment]
Glad to hear! You're right all these things should go in the documentation. I'll update the docs tomorrow!
