### ISSUE TITLE
Attachments

### ISSUE THREAD

**Issue by maxtar** [porscheinformatik/cucumber-report-db#17]
In logs table headers contains following values:
"Step	 Status	Duration	Attachments"
What means "Attachments"? How I can use it?

**Comment by klausbayrhammer** [comment]
Ah your're right thats a bug right now. When you use cucumber you can embed attachments like screenshots/videos/etc. to a formatter. In case of the HTMLFormatter the pictures/videos are displayed. In case of the MongoDBFormatter the attachments are stored in the MongoDB (GridFS) and should be displayed when you open browse in the feature-view of the cucumber-report-db.

The example MongoDBFormatter embeds an image - you can take a look at the code [RpnCalculatorStepdefs](https://github.com/porscheinformatik/cucumber-report-db/blob/master/cucumber-formatter/src/test/java/at/porscheinformatik/cucumber/formatter/RpnCalculatorStepdefs.java) Line 56-57

As of yet storing the attachments works, but we have a problem displaying them. I'll fix it ASAP. Thanks for reporting it!

**Comment by maxtar** [comment]
Thanx, for example!

**Comment by klausbayrhammer** [comment]
The supported attachments types (bmp, png and mp4) now work in current version. I'll update the [Heroku Demo App](https://cucumber-report-db.herokuapp.com) today with some sample runs and attachments

**Comment by maxtar** [comment]
Is it correct test? https://cucumber-report-db.herokuapp.com/#/reports/product_version/features/2015-01-26T16:18:43.000Z/feature/basic-arithmetic I don't see attached. :)

**Comment by klausbayrhammer** [comment]
I have just deployed the new version on heroku - sorry for the delay. You can check it out (images and videos) with the latest test i ran against the heroku app https://cucumber-report-db.herokuapp.com/#/reports/product_version/features/2015-01-28T09:46:01.000Z/feature/basic-arithmetic

**Comment by maxtar** [comment]
Yeah, it looks fine! :)
