### ISSUE TITLE
Need add table data

### ISSUE THREAD

**Issue by maxtar** [porscheinformatik/cucumber-report-db#18]
In log need to add table data. Better like expanding element.

**Comment by klausbayrhammer** [comment]
I'm not quite sure in which view we should add the table data. You are refering to examples of scenario outlines right?

**Comment by maxtar** [comment]
Yeah. I mean examples of sceanario outlines. :)

**Comment by klausbayrhammer** [comment]
Yes that's missing at the moment. I'll have a bit of spare time during the weekend. I'll give it a try. Thanks for reporting it!

**Comment by klausbayrhammer** [comment]
I've added a first draft in 9ec95effc91102cc070839bfdd61a9d0fb321132, but I'm not quite satisfied with the layout. I've deployed the newest version on [heroku](https://cucumber-report-db.herokuapp.com/#/reports/product_version/features/2015-01-28T09:46:01.000Z/feature/basic-arithmetic) - can you take a look at it?

**Comment by maxtar** [comment]
Looks fine!

**Comment by maxtar** [comment]
But I doesn't see expands and collapse table. :)

**Comment by DaHu4wA** [comment]
Hello!
I just added a Show/Hide button in commit: https://github.com/porscheinformatik/cucumber-report-db/commit/2fb06de8a5f060b3240cb6ca6c5a1f25e347c603

**Comment by maxtar** [comment]
Thanx!
