### ISSUE TITLE
Error show graph

### ISSUE THREAD

**Issue by maxtar** [porscheinformatik/cucumber-report-db#21]
When try to see graph get error: "Data column(s) for axis #0 cannot be of type string×". When select filter different from "all' it's work.

**Comment by klausbayrhammer** [comment]
I've deployed a new version including the bugfix on the [heroku demo](https://cucumber-report-db.herokuapp.com/#/statistics/product_version/type/ColumnChart/limit/0).

**Comment by maxtar** [comment]
Thanx, will update.

**Comment by maxtar** [comment]
ok, passed. :)
