### ISSUE TITLE
Allow embedding of all mime-types

### ISSUE THREAD

**Issue by klausbayrhammer** [porscheinformatik/cucumber-report-db#29]
In 57d8fbfe6af7e79a899d1781750e0b3f1420d4e4 we have introduced the feature of embedding zip-files with a download-link in the report. It would be nice if we could embed all possible mime-types and provide download-links for the attachments in the report.

**Comment by klausbayrhammer** [comment]
I've deployed a new version on [heroku](https://cucumber-report-db.herokuapp.com/#/reports/product_version/features/2015-03-16T18:28:57.000Z/feature/basic-arithmetic). You can check out the embedding of logfiles and zips.

Nevertheless there are two, probably minor, issues with the current implementation. Firstly the file extension of the attachment is the subtype of the mimetype (if no special configuration given). That may not be correct in all cases. Secondly there are two special configs (image/jpeg is mapped to .jpg and text/plain is mapped to .log). While I'm confortable with the jpg config one I'm not so sure with the .log config. But I think it's more likely that someone is attaching logfiles than textfiles to a test-run.

**Comment by DaHu4wA** [comment]
Thank you very much :+1:
