### ISSUE TITLE
The "< >" symbols used by  org.junit.ComparisonFailure are affecting the display of the exception inside the Error Log modal 

### ISSUE THREAD

**Issue by jaubuchon** [porscheinformatik/cucumber-report-db#33]
The "< >" symbols used by  org.junit.ComparisonFailure are affecting the display of the exception inside the Error Log modal.

Tested browser: Chrome Version 39.0.2171.71 m

**Scenario:**
![image](https://cloud.githubusercontent.com/assets/1075511/6921203/3f06c334-d791-11e4-9cec-96b0979d8636.png)

**Failed exception displayed in console (pretty-formatter):**
![image](https://cloud.githubusercontent.com/assets/1075511/6921294/e4269326-d791-11e4-853e-21077ff1756f.png)

**Failed exception displayed in cucumber-report-db:**
![image](https://cloud.githubusercontent.com/assets/1075511/6921304/fc75616e-d791-11e4-9db2-582ff46ad33b.png)

**Inside the DOM view#1**
![image](https://cloud.githubusercontent.com/assets/1075511/6921410/aefbbe96-d792-11e4-967a-a445bd2911fa.png)

**Inside the DOM view#2**
![image](https://cloud.githubusercontent.com/assets/1075511/6921469/10046382-d793-11e4-8575-1ab4eb55a8b9.png)

**Comment by jaubuchon** [comment]
Maybe enconding the "<" and ">" by "&lt;" and "&gt;" would resolve the issue?

**Comment by klausbayrhammer** [comment]
Thanks for the bug report and the perfect analysis! Should be working now - I've deployed a new version on [heroku](https://cucumber-report-db.herokuapp.com/#/reports/product_version/features/2015-03-31T16:17:12.000Z/feature/scenarios-with-exceptions). Before closing the issue I'll try to track down other possible escaping.

**Comment by jaubuchon** [comment]
Wow! I'm *really* impressed by the speed you resolved this issue! 

I have just deploy the new version and it fixed the problem like a charm!

Tanx a lot Klaus!
