### ISSUE TITLE
If an Exception is thrown during a @before hook, in the report, the scenario is displayed as "passed"

### ISSUE THREAD

**Issue by jaubuchon** [porscheinformatik/cucumber-report-db#34]
If an Exception is thrown during a @before hook, in the report, the scenario is displayed as "passed".

![feature-view](https://cloud.githubusercontent.com/assets/1075511/8380739/587c2676-1bf5-11e5-8c3a-cf983036d980.PNG)

But when I'm looking at the console, the scenario is marked as failed.
![console-view](https://cloud.githubusercontent.com/assets/1075511/8380843/1dcf511e-1bf6-11e5-8843-29d63cc1d8f3.PNG)

Also, if all the scenarios inside the feature are having the same problem, the feature status is marked as "Ok" and the time spent is marked as "Nan:Nan:Nan".

![report-view](https://cloud.githubusercontent.com/assets/1075511/8380742/5b72f9c2-1bf5-11e5-92b5-29b34466ea09.PNG)

**Comment by klausbayrhammer** [comment]
Thanks for reporting the issue - I'll take a at it this weekend.

**Comment by klausbayrhammer** [comment]
The fix is deployed on [Heroku](https://cucumber-report-db.herokuapp.com/#/reports/product_version/features/2015-06-28T17:16:13.000Z/feature/check-whether-an-exception-in-the-before-hook-doesn't-mess-up-the-report) and released in [1.1.0.RC21](https://github.com/porscheinformatik/cucumber-report-db/releases/tag/1.1.0.RC21)

**Comment by jaubuchon** [comment]
Just tested and it's working perfectly! 

Thank you klausbayrhammer!

**Comment by klausbayrhammer** [comment]
Glad to hear! I'm not 100% satisfied with the solution because the errormessage/stacktrace is not shown in the report but I'm not quite sure where to intercept the `@before` exceptions. I'll put some thoughts - maybe there's an elegant solution.

**Comment by jaubuchon** [comment]
On my side, I attach a log file to each scenario in order to make them available inside the report. But I had a problem with the exceptions thrown during a scenario, I didn't know how to append them in log4j. I ask the question on the cukes group and someone propose me a solution that I will implement soon:

https://groups.google.com/forum/#!topic/cukes/briGKl5ZEcg
